trigger:
  branches:
    exclude:
      - "*"

jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - script: mvn clean install -B
    displayName: 'Build Step'

- job: Test
  displayName: 'Test'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: mvn test
    displayName: 'Test Step'

- job: Deploy
  displayName: 'Deploy'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo 'Deploying to staging environment...'
    displayName: 'Deploy to Staging'
  - script: echo 'Deploying to production environment...'
    displayName: 'Deploy to Production'
