trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'

- script: |
    ls $(System.DefaultWorkingDirectory)/target
    ls -ltrh $(Build.ArtifactStagingDirectory)
  displayName: 'List contents of target directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target/helloworld.war'
    ArtifactName: 'SushArtifact'

- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'

- task: JaCoCo@0
  inputs:
    classFilesDirectories: 'target/classes'
    sourceDirectories: 'src/main/java'
    exclusionFiles: |
      **/*Test*.*
      **/*test*.*
    includeBranchCoverage: true

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'




    
 
  



